spring:
  cloud:
    stream:
      bindings:
        cart-input-channel:
          destination: cart-events
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              processing.guarantee: exactly_once
        
              